package com.antonycc.oidc;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import software.amazon.awscdk.App;
import software.amazon.awscdk.Environment;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Test to verify that CognitoStack produces deterministic CloudFormation logical IDs
 * without autogenerated hash suffixes, addressing the issue described in the problem statement.
 */
class CognitoStackDeterministicNamingTest {

  @Test
  void cognitoStackProducesDeterministicLogicalIds() throws IOException {
    var app = new App();
    Environment env = Environment.builder().account("123456789012").region("us-east-1").build();

    // Create CognitoStack with test parameters
    CognitoStack cognitoStack =
        new CognitoStack(
            app,
            "CognitoStack-test",
            CognitoStackProps.builder()
                .env(env)
                .envName("test")
                .domainName("oidc.example.com")
                .cognitoDomainPrefix("oidc-test-xyz")
                .authCertificateArn("arn:aws:acm:us-east-1:123456789012:certificate/test")
                .hostedZoneName("example.com")
                .hostedZoneId("Z000EXAMPLE")
                .build());

    // Synthesize to get the CloudFormation template
    var cloudAssembly = app.synth();
    var stackArtifact = cloudAssembly.getStackByName("CognitoStack-test");
    Path templatePath = Path.of(stackArtifact.getTemplateFullPath());
    String templateJson = Files.readString(templatePath);

    // Parse the CloudFormation template JSON
    ObjectMapper objectMapper = new ObjectMapper();
    JsonNode template = objectMapper.readTree(templateJson);
    JsonNode resources = template.get("Resources");

    // Verify all resource logical IDs are deterministic (no hash suffixes)
    String expectedPrefix = "oidcexamplecomtest"; // domain "oidc.example.com" + env "test"

    // 1. UserPool should have deterministic logical ID
    String userPoolLogicalId = expectedPrefix + "UserPool";
    assertTrue(resources.has(userPoolLogicalId), 
        "UserPool should have deterministic logical ID: " + userPoolLogicalId);
    assertEquals("AWS::Cognito::UserPool", resources.get(userPoolLogicalId).get("Type").asText());

    // 2. UserPoolDomain should have deterministic logical ID  
    String domainLogicalId = expectedPrefix + "CognitoDomain";
    assertTrue(resources.has(domainLogicalId),
        "UserPoolDomain should have deterministic logical ID: " + domainLogicalId);
    assertEquals("AWS::Cognito::UserPoolDomain", resources.get(domainLogicalId).get("Type").asText());

    // 3. UserPoolClient should have deterministic logical ID
    String clientLogicalId = expectedPrefix + "WebClient";
    assertTrue(resources.has(clientLogicalId),
        "UserPoolClient should have deterministic logical ID: " + clientLogicalId);
    assertEquals("AWS::Cognito::UserPoolClient", resources.get(clientLogicalId).get("Type").asText());

    // 4. UserPoolIdentityProvider should have deterministic logical ID
    String idpLogicalId = expectedPrefix + "OidcIdp";
    assertTrue(resources.has(idpLogicalId),
        "UserPoolIdentityProvider should have deterministic logical ID: " + idpLogicalId);
    assertEquals("AWS::Cognito::UserPoolIdentityProvider", resources.get(idpLogicalId).get("Type").asText());

    // Verify no resources have autogenerated hash suffixes (8+ alphanumeric characters)
    resources.fieldNames().forEachRemaining(logicalId -> {
      // Skip CDKMetadata which legitimately has a UUID
      if (logicalId.equals("CDKMetadata")) return;
      
      assertFalse(logicalId.matches(".*[A-F0-9]{8,}$"), 
          "Resource logical ID should not have autogenerated hash suffix: " + logicalId);
    });

    // Verify the physical names are set correctly
    assertEquals("oidc-example-com-test-user-pool", 
        resources.get(userPoolLogicalId).get("Properties").get("UserPoolName").asText());
  }
}
